# Generated by Django 2.0.5 on 2018-05-07 04:30

import boogie.fields.enum_field
import cs_classroom.classrooms.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='comments_policy',
            field=boogie.fields.enum_field.EnumField(cs_classroom.classrooms.models.CommentPolicyEnum, blank=True, is_string=False, null=True),
        ),
    ]
